### ISSUE TITLE
Ansible Common Task Failure

### ISSUE THREAD

**Issue by b1gbroth3r** [maliciousgroup/GOADvSphere#1]
Hey there. I was just curious if you were running into Ansible task failures during your beta testing. The repo does a great job automating everything for me until the Ansible roles start. Specifically, the Ansible task that seems to fail each time is the
 `TASK [common : Upgrade module PowerShellGet to fix accept license issue on last windows ansible version]` task.

I'm pretty sure it's pointing to https://github.com/Orange-Cyberdefense/GOAD/blob/4dfbbf637577f21c5918c3d36ff439fd0439077a/ansible/roles/common/tasks/main.yml#L23 

Since it seems to pull the Ansible tasks/roles from the original GOAD repo, I wasn't sure if I should raise the issue here or there. Am happy to close and repost to the GOAD repo if you prefer!

The error output in its entirety is the following snippet:
`fatal: [dc03]: FAILED! => {"changed": true, "cmd": "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12\nInstall-PackageProvider -Name NuGet -Force\nInstall-Module PowerShellGet -Force", "delta": "0:00:10.296897", "end": "2023-12-27 16:11:41.700072", "msg": "non-zero return code", "rc": 1, "start": "2023-12-27 16:11:31.403174", "stderr": "Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package \r\nprovider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.\r\nAt line:2 char:1\r\n+ Install-PackageProvider -Name NuGet -Force\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-Pac \r\n   kageProvider], Exception\r\n    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackagePro \r\n   vider\r\n \r\nException calling \"ShouldContinue\" with \"2\" argument(s): \"Windows PowerShell is in NonInteractive mode. Read and \r\nPrompt functionality is not available.\"\r\nAt C:\\Program Files\\WindowsPowerShell\\Modules\\PowerShellGet\\1.0.0.1\\PSModule.psm1:7392 char:8\r\n+     if($Force -or $psCmdlet.ShouldContinue($shouldContinueQueryMessag ...\r\n+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : PSInvalidOperationException\r\n \r\nInstall-Module : NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201' \r\nor newer version of NuGet provider is installed.\r\nAt line:3 char:1\r\n+ Install-Module PowerShellGet -Force\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidOperation: (:) [Install-Module], InvalidOperationException\r\n    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Install-Module", "stderr_lines": ["Install-PackageProvider : No match was found for the specified search criteria for the provider 'NuGet'. The package ", "provider requires 'PackageManagement' and 'Provider' tags. Please check if the specified package has the tags.", "At line:2 char:1", "+ Install-PackageProvider -Name NuGet -Force", "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackageProvider) [Install-Pac ", "   kageProvider], Exception", "    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackagePro ", "   vider", " ", "Exception calling \"ShouldContinue\" with \"2\" argument(s): \"Windows PowerShell is in NonInteractive mode. Read and ", "Prompt functionality is not available.\"", "At C:\\Program Files\\WindowsPowerShell\\Modules\\PowerShellGet\\1.0.0.1\\PSModule.psm1:7392 char:8", "+     if($Force -or $psCmdlet.ShouldContinue($shouldContinueQueryMessag ...", "+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException", "    + FullyQualifiedErrorId : PSInvalidOperationException", " ", "Install-Module : NuGet provider is required to interact with NuGet-based repositories. Please ensure that '2.8.5.201' ", "or newer version of NuGet provider is installed.", "At line:3 char:1", "+ Install-Module PowerShellGet -Force", "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : InvalidOperation: (:) [Install-Module], InvalidOperationException", "    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Install-Module"], "stdout": "", "stdout_lines": []}`

**Comment by maliciousgroup** [comment]
Make sure the Windows VMs have internet access for the ansible configuration part. I think I ran into this same issue when the Windows VM running the ansible scripts didn't have internet access. The pfSense rules should have allowed access from LAN to WAN during the setup process. Check if they have internet access, and if they do I will try to help from there. Also, I have run into ansible issue where I had to run the setup process twice before the ansible portion took.

**Comment by b1gbroth3r** [comment]
Awesome, I appreciate the fast reply. I'll run the script again and check internet access and the pfSense rules and report back.

**Comment by b1gbroth3r** [comment]
Yep found the culprit, the VMs could ping out but DNS resolution was failing. Once I enabled `Enable Forwarding Mode` for the `DNS Query Forwarding` setting under Services -> DNS Resolver -> General Settings, the Ansible task stopped failing!

**Comment by maliciousgroup** [comment]
Awesome! 

In the next few days I am going to add the Elastic EDR Ubuntu 22.04 machine as an option for those wanting to have a EDR setup on each machine. I have some automation to work out, but it should be added before to much longer.

**Comment by maliciousgroup** [comment]
Solved.
